/**
 * montage.mjs — the shared contact-sheet page shell for the on-demand capture tools.
 *
 * Extracted from `tools/sheet.mjs` when the podium sweep arrived: the page chrome (dark
 * shell, card grid, chip/banner styling) is identical across tools, but **card rendering
 * stays per-tool** — the chips differ (the HUD sheet reports feed rows and quality tier,
 * the podium sheet reports outcome and winner slot), so each tool builds its own
 * `cardsHtml` and passes it in.
 *
 * The `banner` slot is not decoration. Every tool here captures something that is NOT a
 * golden render — headless SwiftShader, forced state, held frames — and the montage has to
 * say so on its own face, plus name whatever the run could not reach. That is the
 * D-SHEET-1 discipline in HTML form.
 */

import { ROOT_TOKENS } from "./ccStyle.mjs";

/** HTML-escape for interpolated card text. */
export const esc = (s) =>
  String(s ?? "").replace(/[&<>"]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[ch]);

/**
 * Render a full montage page.
 *
 * @param {object} o
 * @param {string} o.title      Sheet name, e.g. "HUD contact sheet". Becomes `<title>` as
 *   "Cart Clash — <title>" and the `<h1>` as an uppercased "CART CLASH — <TITLE>".
 * @param {string} o.stamp      One-line sub-header (timestamp, cell count, pin summary).
 * @param {string} o.banner     Inner HTML of the caveat banner — pre-escaped by the caller,
 *   because it deliberately carries markup (`<b>`, `<code>`, `<br>`).
 * @param {string} o.cardsHtml  Pre-rendered `.card` elements (per-tool).
 * @param {string} [o.footer]   Inner HTML of the footer line; defaults to a generic note.
 * @returns {string}
 */
export function montagePage({ title, stamp, banner, cardsHtml, footer }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cart Clash — ${esc(title)}</title>
<style>
${ROOT_TOKENS}
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font:14px/1.5 system-ui,Segoe UI,sans-serif; }
  .shell { max-width:1440px; margin:0 auto; padding:20px 24px 48px; }
  h1 { margin:0 0 2px; font-size:20px; letter-spacing:3px; font-weight:800; }
  h1 .neon { color:var(--neon); text-shadow:0 0 18px rgba(255,45,149,.55); }
  .stamp { color:var(--dim); font-size:12px; }
  .banner { margin:16px 0 20px; padding:12px 16px; border:1px solid rgba(255,45,149,.45);
            border-radius:8px; background:var(--panel); font-size:13px; }
  .banner b { color:var(--neon); }
  .cards { display:grid; grid-template-columns:repeat(auto-fill, minmax(300px, 1fr)); gap:12px; }
  .card { background:var(--panel2); border:1px solid var(--edge); border-radius:10px; overflow:hidden; }
  .card:hover { border-color:var(--edge2); }
  .card.bad { border-color:var(--bad); }
  .card img { width:100%; display:block; aspect-ratio:16/9; object-fit:cover; background:#000; }
  .cardbody { padding:10px 12px; font-size:12px; }
  .dim { color:var(--dim); }
  .err { color:var(--bad); }
  .chip { display:inline-block; margin:4px 4px 0 0; padding:1px 7px; border:1px solid var(--edge2);
          border-radius:999px; font-size:11px; color:var(--cyan); }
  .chip.warn { color:var(--warn); border-color:rgba(255,194,75,.4); }
  a { color:var(--cyan); }
  footer { margin-top:28px; padding-top:16px; border-top:1px solid var(--edge); color:var(--dim); font-size:12px; }
</style>
</head>
<body>
  <div class="shell">
    <h1>CART <span class="neon">CLASH</span> — ${esc(title).toUpperCase()}</h1>
    <div class="stamp">${stamp}</div>

    <div class="banner">
${banner}
    </div>

    <div class="cards">
${cardsHtml}
    </div>

    <footer>${footer ?? "Generated by the Cart Clash capture toolkit."}</footer>
  </div>
</body>
</html>
`;
}
