#!/usr/bin/env node
/**
 * Download latin woff2 files from Google Fonts CSS API into public/fonts/
 * and write a self-hosted fonts.css. Run: node scripts/fetch-fonts.mjs
 */
import { writeFileSync, mkdirSync, readdirSync, statSync, unlinkSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, "..", "public", "fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// * Only faces the app actually references (2026-07 asset audit): Michroma,
// * Space Grotesk, and Space Mono 700 had zero call sites and were dropped.
// * Space Mono 400 stays — touch controls + dev FPS overlay use it.
const families = [
  "Road+Rage",
  "Russo+One",
  "Goldman:wght@400;700",
  "Bungee",
  "Space+Mono",
];

const cssUrl =
  "https://fonts.googleapis.com/css2?" +
  families.map((f) => `family=${f}`).join("&") +
  "&display=swap";

mkdirSync(outDir, { recursive: true });

const cssRes = await fetch(cssUrl, { headers: { "User-Agent": UA } });
if (!cssRes.ok) {
  console.error(`[fetch-fonts] CSS request failed: ${cssRes.status}`);
  process.exit(1);
}
const css = await cssRes.text();

const urlRe = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g;
const urls = [...new Set([...css.matchAll(urlRe)].map((m) => m[1]))];
if (urls.length === 0) {
  console.error("[fetch-fonts] No woff2 URLs in CSS — API shape may have changed.");
  process.exit(1);
}
console.log(`[fetch-fonts] ${urls.length} woff2 file(s)`);

/** @type {Map<string, string>} */
const map = new Map();
for (const url of urls) {
  const parts = new URL(url).pathname.split("/").filter(Boolean);
  const family = parts[1] || "font";
  const file = parts[parts.length - 1] || "file.woff2";
  const local = `${family}-${file}`;
  map.set(url, local);

  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) {
    console.error(`[fetch-fonts] download failed ${url} → ${res.status}`);
    process.exit(1);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(path.join(outDir, local), buf);
  console.log(`  ${(buf.length / 1024).toFixed(1).padStart(7)} KB  ${local}`);
}

let localCss = css.replace(urlRe, (_, u) => `url(./${map.get(u)})`);
if (localCss.includes("fonts.gstatic.com")) {
  console.error("[fetch-fonts] CSS still references fonts.gstatic.com after rewrite");
  process.exit(1);
}

// * Keep latin faces only — english UI; drops vietnamese / latin-ext files from disk.
const pairRe = /\/\* ([\w-]+) \*\/\s*(@font-face\s*\{[\s\S]*?\n\})/g;
/** @type {string[]} */
const latinFaces = [];
/** @type {Set<string>} */
const keepFiles = new Set();
let m;
while ((m = pairRe.exec(localCss)) !== null) {
  if (m[1] !== "latin") continue;
  latinFaces.push(`/* latin */\n${m[2]}`);
  const file = m[2].match(/url\(\.\/([^)]+)\)/);
  if (file) keepFiles.add(file[1]);
}
if (latinFaces.length === 0) {
  console.error("[fetch-fonts] No latin @font-face blocks found");
  process.exit(1);
}

const banner = `/* Self-hosted Cart Clash UI fonts (latin woff2 only).
 * Generated by scripts/fetch-fonts.mjs — re-run to refresh.
 * Sources: Google Fonts, SIL Open Font License 1.1.
 */
`;
writeFileSync(path.join(outDir, "fonts.css"), banner + latinFaces.join("\n") + "\n");

for (const name of readdirSync(outDir)) {
  if (!name.endsWith(".woff2")) continue;
  if (!keepFiles.has(name)) {
    unlinkSync(path.join(outDir, name));
    console.log(`[fetch-fonts] removed non-latin ${name}`);
  }
}

let total = 0;
for (const name of readdirSync(outDir)) {
  if (name.endsWith(".woff2")) total += statSync(path.join(outDir, name)).size;
}
console.log(
  `[fetch-fonts] Wrote fonts.css (${latinFaces.length} latin faces) + ${(total / 1024).toFixed(0)} KB woff2 → public/fonts/`,
);
