// gameState.js — STORE-1 Lever A shim. Function-only re-export of gameStore.js.
// Do not re-export gameStore or RoundPhase. Lever B deletes this file.
export {
  getRoundState,
  setRoundPhase,
  syncRoundPhase,
  addScore,
  pickTimerWinner,
  recordHit,
  clearLastHitBy,
  setRoundScores,
  setRoundStartedAtMs,
  setRoundCountdownStartedAtMs,
  setRoundWinnerSlotIndex,
  setRoundEndReason,
  clearAllHits,
  resetRoundToLobby,
  getRoundScores,
  isScoreTied,
  setSuddenDeath,
  setSuddenDeathWinCallback,
  setLocalCombo,
  getLastHitBy,
  replaceLastHitBy,
  getLastScoringHitAt,
  setLastScoringHitAt,
} from "./stores/gameStore.js";
